### ISSUE TITLE
Master.csv not available

### ISSUE THREAD

**Issue by pssguy** [keberwein/moneyball#1]
```
library(baseballDBR)
get_bbdb(table = "Master")
cannot open URL 'https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/Master.csv': HTTP status was '404 Not Found'Error in file(file, "rt") : cannot open the connection
```
Other tables I have tried work smoothly

If I download all tables, I get 27 (as stated in get_bbdb() info) but Master is not one of them

```
> get_bbdb(AllTables = TRUE)
trying URL 'https://github.com/chadwickbureau/baseballdatabank/archive/master.zip'
Content type 'application/zip' length unknown
downloaded 8.5 MB
```

```
[1] "Teams"               "Appearances"         "Parks"               "FieldingPost"       
 [5] "Batting"             "AwardsSharePlayers"  "SeriesPost"          "AwardsPlayers"      
 [9] "People"              "FieldingOFsplit"     "Managers"            "AwardsManagers"     
[13] "Pitching"            "BattingPost"         "PitchingPost"        "Fielding"           
[17] "AwardsShareManagers" "HomeGames"           "FieldingOF"          "TeamsHalf"          
[21] "AllstarFull"         "HallOfFame"          "Schools"             "ManagersHalf"       
[25] "TeamsFranchises"     "Salaries"            "CollegePlaying"
```

On a  side note, your tables includes 2016 whilst the latest Lahman package is still 2015. Are they still testing their data before issuing?

**Comment by keberwein** [comment]
In the Baseball Databank schema, the `Master` table is called `People`. This is one of the very small differences between the Lahman Database and the Baseball Databank. I'm going to close this issue, but open another issue to address this since I know it will probably happen again.

```library(baseballDBR)
get_bbdb(table = "People")
```

As far as the Lahman package, CRAN has limitations on how much data can be included in a package (5 MB I think), and the `Lahman` package is currently pushing that. I'm not sure how they plan to update. If you go to Sean Lahman's [website](http://www.seanlahman.com/baseball-archive/statistics/), the 2016 data are up, and have been for a while.

**Comment by pssguy** [comment]
Thanks for swift response. That did the trick
Lahman did not seem to be updated until August last year so maybe something is imminent; but thanks to you that isn't a problem

**Comment by keberwein** [comment]
NP:) The only way I could see how the Lahman package would continue to be updated is if they cut off some of the earlier pre-modern era years... Either way, that's kind of what inspired me to write this package. Glad I could help, and thanks for pointing the issue on the `Master` table!
